name: deoldify
channels:
- fastai
- pytorch
- conda-forge
- defaults
dependencies:
- python>=3.7.3
- fastai=1.0.51
- pytorch=1.0.1
- tensorboardX=1.6
- youtube-dl>=2019.4.17
- ipykernel
- pillow<9
- ffmpeg-python
- opencv-python-headless>=3.3.0.10
- wandb
